import { z } from 'zod'

export const IdTypeSchema = z.enum([
  'ID_ISIN',
  'ID_BB_UNIQUE',
  'ID_SEDOL',
  'ID_COMMON',
  'ID_WERTPAPIER',
  'ID_CUSIP',
  'ID_BB',
  'ID_ITALY',
  'ID_EXCH_SYMBOL',
  'ID_FULL_EXCHANGE_SYMBOL',
  'COMPOSITE_ID_BB_GLOBAL',
  'ID_BB_GLOBAL_SHARE_CLASS_LEVEL',
  'ID_BB_GLOBAL',
  'ID_BB_SEC_NUM_DES',
  'ID_BB_SEC_NUM',
  'ID_CINS',
  'ID_BELGIUM',
  'ID_DENMARK',
  'ID_FRANCE',
  'ID_JAPAN',
  'ID_LUXEMBOURG',
  'ID_NETHERLANDS',
  'ID_POLAND',
  'ID_PORTUGAL',
  'ID_SWEDEN',
  'ID_SHORT_CODE',
]).or(z.string())

export const ExchCodeSchema = z.enum([
  '24X National', 'A0', 'AA', 'AB', 'ABIDJAN', 'ABTS', 'ABU DHABI', 'AC', 'ACE', 'ACXI',
  'AD', 'ADE', 'ADX', 'AEQUITAS NEO LIT', 'AERB', 'AERC', 'AF', 'AFE', 'AG', 'AH',
  'AI', 'AIAF', 'AJ', 'AL', 'ALCN', 'ALGIERS', 'ALL GERMAN SE', 'AM', 'AME', 'AMMAN FIN MKT',
  'ANTWERP', 'AO', 'AP', 'APX', 'AQ', 'Aquis', 'AR', 'ARKM', 'ARMENIA', 'AS',
  'ASP', 'ASUNCION', 'ASX', 'AT', 'ATA', 'ATHENS', 'AU', 'AUSTRALIA', 'AV', 'AW',
  'AX', 'AY', 'AZ', 'B1', 'B2', 'B3', 'B4', 'BA', 'BAHAMAS', 'BAHRAIN',
  'BAKU', 'BANGALORE', 'BANJA LUKA', 'BARBADOS', 'BARCELONA', 'BATS', 'BB', 'BBOX', 'BBSP', 'bbsp',
  'BBX', 'BC', 'BCEX', 'BCF', 'BD', 'BDP', 'BEIJING', 'BEIRUT', 'BELARUS', 'BELGRADE',
  'BEQU', 'bequ', 'BERLIN', 'BERMUDA', 'BERN', 'BEVSA', 'BF', 'BFLY', 'bfly', 'BFNX',
  'bfnx', 'BFO', 'BFRX', 'bfrx', 'BFX', 'BG', 'BGC', 'BGON', 'bgon', 'BGSP',
  'BH', 'BI', 'BIDS', 'BILBAO', 'BINC', 'binc', 'BITZ', 'BIVA', 'BJEX', 'BK',
  'BL3P', 'BLC2', 'blc2', 'BLCR', 'blcr', 'Blue Ocean ATS', 'BM', 'BMF', 'BN', 'BNCE',
  'bnce', 'BNDX', 'BNF', 'BNUS', 'bnus', 'BO', 'Bodiva', 'BOLSA CENTROAMER', 'BOLSA NACL VALOR', 'Bondvision',
  'BORSA ISTANBUL', 'BOTSWANA', 'BOV', 'BP', 'Bpm', 'bpnd', 'BPVB', 'BQ', 'BR', 'BRATISLAVA',
  'BRJ', 'BS', 'BSE', 'BT', 'BT38', 'BTBA', 'btba', 'BTBU', 'BTBY', 'BTCA',
  'btcb', 'BTHB', 'bthb', 'BTMX', 'btmx', 'BTRK', 'btrk', 'BTRX', 'btrx', 'BTS',
  'BTSH', 'BTSO', 'btso', 'BU', 'BUCHAREST', 'BUDAPEST', 'BUENOS AIRES', 'BULGARIA', 'BULL', 'BURGUNDY',
  'BURSA MALAYSIA', 'BV', 'BVAV', 'BVL', 'BW', 'BX', 'BX - SWISS', 'BXTH', 'BY', 'BYBT',
  'BZ', 'C1', 'C2', 'C3', 'CA', 'CARACAS', 'CASABLANCA', 'CAYMAN ISLANDS', 'CB', 'CBD',
  'CBF', 'CBO', 'CBOE', 'CBSE', 'cbse', 'CBT', 'CC', 'ccck', 'CCO', 'CCT',
  'CCX', 'CD', 'CDE', 'CE', 'CEG', 'CENT ANOTACIONE', 'CEXI', 'cexi', 'CF', 'CFF',
  'CFLR', 'CG', 'CH', 'CHANNEL ISLANDS', 'CHI-X', 'Chi-X Australia', 'CHICAGO', 'CHINA INTERBANK', 'CHONGWA ASSET EX', 'CI',
  'CJ', 'CK', 'CL', 'CM', 'CME', 'CMF', 'CML3', 'CMX', 'CN', 'CNEX',
  'cnex', 'CNGG', 'CNHD', 'CNMT', 'CNSX', 'CO', 'COLOMBIA', 'COLOMBO', 'CONE', 'cone',
  'COP', 'CP', 'CQ', 'CR', 'CRCO', 'crco', 'CRV2', 'crv2', 'CS', 'CSE',
  'CT', 'CU', 'CUCY', 'cucy', 'CURV', 'curv', 'CV', 'CW', 'CX', 'CY',
  'CYPRUS', 'CZ', 'DAR-ES-SALAAM', 'DB', 'DBS Digital', 'DC', 'DCE', 'DD', 'DE', 'DEB',
  'delt', 'DF', 'DFX', 'DG', 'DGC', 'DH', 'DHAKA', 'DJ', 'DK', 'DL',
  'DM', 'DME', 'DN', 'DOUALA', 'drbt', 'DS', 'DT', 'DU', 'DUBAI FINL MKT', 'DUBLIN',
  'DUSSELDORF', 'DV', 'DVX', 'DX', 'E1', 'E2', 'EA', 'EAST CARIBBEAN', 'EB', 'EC',
  'ED', 'EDX', 'EDXM', 'EEE', 'EG', 'EGX', 'EI', 'EK', 'EL', 'EL SALVADOR',
  'ELECTRONIC CHILE', 'ELX', 'EM', 'EN', 'EO', 'EOC', 'EOE', 'EOP', 'EP', 'EQ',
  'ERI', 'ERIS', 'eris', 'ES', 'ESWATINI', 'ET', 'ETHX', 'EU', 'EUROMTF', 'EUROMTS',
  'EURONEXT-AMSTER', 'EURONEXT-BRUSS', 'EURONEXT-DUBLIN', 'EURONEXT-GRW-MIL', 'EURONEXT-LISBON', 'EURONEXT-MILAN', 'EURONEXT-PARIS', 'EUROTLX', 'EUS', 'EUWAX STUTTGART',
  'EUX', 'EX', 'Extra MOT', 'Extra MOT Pro', 'EXXA', 'EY', 'EZ', 'FA', 'FEX', 'FF',
  'FF ZERTIFIKATE', 'FFE', 'FH', 'FMX', 'FNX', 'FP', 'FPL', 'FRANKFURT', 'FRX', 'FS',
  'FTX', 'FTXX', 'FUKUOKA', 'G1', 'G4', 'GA', 'GACN', 'GATE', 'GB', 'GBT',
  'GC', 'GD', 'GE', 'GEMMA', 'GEORGIA', 'Gettex', 'GF', 'GG', 'GH', 'GHANA',
  'GI', 'Gibraltar', 'GK', 'GL', 'GM', 'GME', 'GMNI', 'gmni', 'GN', 'GQ',
  'GR', 'GS', 'GT', 'GU', 'GUATEMALA', 'GUAYAQUIL', 'GW', 'GY', 'GZ', 'H1',
  'H2', 'HAMBURG', 'HANNOVER', 'HANOI', 'HB', 'HCM CITY EXCH', 'HD', 'HE', 'HEX', 'HI-MTF',
  'HITB', 'hitb', 'HK', 'HKG', 'HKM', 'HM', 'HNX', 'HO', 'HONG KONG', 'HUOB',
  'huob', 'HX', 'I2', 'IA', 'IAD', 'IB', 'IC', 'ICD', 'ICE', 'ICE ECX',
  'ICF', 'ID', 'IDEM', 'IDR', 'IDX', 'IE', 'IEA', 'IF', 'IFE', 'IG',
  'IH', 'IJ', 'IM', 'IN', 'INCH', 'INDIA INX', 'INDONESIA EXCH', 'INDR', 'indr', 'INE',
  'INTERCONTINENTAL', 'INX', 'IO', 'IQ', 'IR', 'IS', 'ISE', 'ISF', 'ISG', 'ISLAND ECN LTD',
  'IST', 'IT', 'ITBI', 'itbi', 'IX', 'IY', 'JA', 'JAMAICA', 'JASDAQ', 'JB',
  'JC', 'JD', 'JE', 'JF', 'JFX', 'JG', 'JI', 'JJ', 'JL', 'JM',
  'JN', 'JO', 'JOHANNESBURG', 'JP', 'JQ', 'JR', 'JS', 'JSE Cent Ord Bk', 'JSE Contrib Prx', 'JT',
  'JU', 'JV', 'JW', 'JX', 'JY', 'KA', 'KAS', 'KAZAKHSTAN', 'KB', 'KCB',
  'KCON', 'kcon', 'KE', 'KF', 'KFE', 'KH', 'KIEV', 'KK', 'KL', 'KN',
  'KORB', 'korb', 'KOREA', 'KOSDAQ', 'KP', 'KQ', 'KRKN', 'krkn', 'KS', 'KT',
  'KUWAIT', 'KX', 'KY', 'KYRGZSTAN', 'KZ', 'L1', 'L3', 'LA', 'LA PAZ', 'LABUAN INTL FIN',
  'LB', 'LC', 'LCLB', 'LD', 'LDX', 'LE', 'LF', 'LG', 'LH', 'LI',
  'LISBON', 'LJUBLJANA', 'LMAX', 'lmax', 'LME', 'LMP', 'LN', 'LO', 'LONDON', 'LONDON INTL',
  'LR', 'LS', 'LSE', 'LSE-RETAIL', 'LT', 'LU', 'LUSAKA', 'LUXEMBOURG', 'LV', 'LX',
  'LY', 'LYON', 'M0', 'MA', 'MACEDONIA', 'MADRAS', 'MADRID', 'MAE', 'MALAWI', 'MALTA',
  'MANAGUA', 'MARF', 'MARSEILLE', 'MAURITIUS', 'MB', 'MBA', 'MC', 'MCE', 'MCI', 'MCT',
  'MCX', 'MD', 'MDE', 'MDX', 'ME', 'MELBOURNE', 'MENDOZA', 'MERC', 'MERJ', 'MERVAL',
  'MET', 'META', 'METD', 'MEXC', 'mexc', 'MEXICO', 'MF', 'MFA', 'MFM', 'MFP',
  'MGE', 'MI', 'MICEX', 'MICEX A1', 'MICEX A2', 'MICEX B', 'MICEX D', 'MICEX Unlisted', 'MICEX V', 'MIF',
  'MIL', 'MILAN', 'MK', 'MM', 'MN', 'MO', 'MOEX Level 1', 'MOEX Level 2', 'MOEX Level 3', 'MONGOLIA',
  'MONTENEGRO', 'MONTEVIDEO', 'MOSCOW', 'MOT', 'MOZAMBIQUE', 'MP', 'MS', 'MSE', 'MSX', 'MT',
  'MTS AMSTERDAM', 'MTS Austria', 'MTS BELGIUM', 'MTS Finland', 'MTS FRANCE', 'MTS Germany', 'MTS GREECE', 'MTS IRELAND', 'MTS Israel', 'MTS PORTUGAL',
  'MTS S.p.A', 'MTS Spain', 'MU', 'MUMBAI', 'MUNICH', 'MUSCAT SECS MKT', 'MV', 'MW', 'MX', 'MY',
  'MZ', 'N2X', 'NA', 'NAGOYA', 'NAIROBI', 'NAMIBIA', 'NANTES', 'NASDAQ', 'NASDAQ DUBAI', 'NASDAQ OMX PHLX',
  'NASDAQ/NCM', 'NASDAQ/NGM', 'NASDAQ/NGS', 'NB', 'NC', 'ND', 'NDM', 'NDX', 'NE', 'NEW YORK',
  'NEW ZEALAND', 'NF', 'NFE', 'NFX', 'NG', 'NGC', 'NGCS', 'NGM', 'NI', 'NIGERIA',
  'NJ', 'NK', 'NL', 'NLX', 'NM', 'NN', 'NO', 'NOMX 1stNorth C', 'NOMX 1stNorth F', 'NOMX 1stNorth S',
  'NOMX COPENHAGEN', 'NOMX HELSINKI', 'NOMX ICELAND', 'NOMX RIGA', 'NOMX STOCKHOLM', 'NOMX TALLINN', 'NOMX VILNIUS', 'NORDIC ABM', 'NOT LISTED', 'NOUVEAU MARCHE',
  'NOVA', 'NP', 'NPE', 'NQ', 'NQL', 'NR', 'NS', 'NSE', 'NSE Australia', 'NSE IFSC',
  'NSE INDIA', 'NSEL', 'NT', 'NV', 'NVDX', 'nvdx', 'NW', 'NX', 'NY', 'NYB',
  'NYF', 'NYM', 'NYSE AMERICAN', 'NYSE ARCA', 'NYSE BONDMATCH', 'NZ', 'NZX', 'OBX', 'OC', 'OC_NA',
  'OCG', 'OD', 'ODE', 'OF', 'OKCN', 'okcn', 'OKEX', 'okex', 'OM', 'OMEGA CANADA ATS',
  'OMP', 'ORCA', 'OS', 'OSAKA', 'OSAKA 2', 'OSE', 'OSLO', 'oslx', 'OTC BB', 'OTC US',
  'OU', 'P2', 'PA', 'PAKISTAN', 'PALESTINE', 'PANAMA', 'PB', 'PBT', 'PC', 'PD',
  'PDEx', 'PE', 'PEX', 'PF', 'PFTS', 'PG', 'PHILIPPINES', 'PHL', 'PINK SHEETS', 'PK',
  'PKSP', 'pksp', 'PL', 'PLX', 'PM', 'PMI', 'PMX', 'PN', 'PNX', 'PO',
  'POLO', 'polo', 'PORT MORESBY', 'PORTAL', 'PP', 'PQ', 'PRAGUE', 'PRG', 'PRO SEC MKT(PSM)', 'PS',
  'PURE TRADING', 'PW', 'PX', 'PZ', 'QATAR', 'QD', 'QE', 'QF', 'QG', 'QH',
  'QM', 'QN', 'QSP3', 'qsp3', 'QT', 'QU', 'QUITO', 'QUON', 'Quotrix', 'QX',
  'RASDAQ', 'RAYA', 'RAYC', 'RB', 'RC', 'RE', 'RF', 'RFX', 'RG', 'RIO DE JANEIRO',
  'RM', 'RN', 'RO', 'ROFEX', 'RP', 'RQ', 'RR', 'RS', 'RT', 'RTS',
  'RU', 'RUSSIAN TRADING', 'RW', 'RWANDA', 'RX', 'RZ', 'S1', 'S2', 'S3', 'S4',
  'SA', 'SAF', 'SANTIAGO', 'SANTO DOMINGO', 'SAO PAULO', 'SARAJEVO', 'SAUDI ARABIA', 'SB', 'SBA', 'SC',
  'SCE', 'SCIEX', 'SCOACH-FRANKFURT', 'SD', 'SE', 'SEDEX-Milan', 'SEND', 'SF', 'SFE', 'SG',
  'SGX', 'SGX-ST', 'SH', 'SHANGHAI', 'SHENZHEN', 'SHF', 'SI', 'SIB', 'SIBE', 'SICEX',
  'SINGAPORE', 'SINGAPORE MAINBD', 'SISBEX', 'SIX', 'SIX Digital', 'SIX Europe LTD', 'SIX STRUCTURED', 'SIX Swiss (SP)', 'SJ', 'SK',
  'SL', 'SLOVAK', 'SM', 'SME', 'SN', 'SO', 'SOP', 'SP', 'SPCEX', 'SPX',
  'SQ', 'SR', 'SS', 'SSE', 'ST', 'St. Petersburg', 'STMP', 'stmp', 'STRASBOURG', 'STUTTGART',
  'SU', 'SUSH', 'sush', 'SV', 'SW', 'SX', 'SXHA', 'sxha', 'SY', 'SZ',
  'T1', 'T2', 'T3', 'TA', 'TAD', 'Taipei', 'TAIWAN', 'TASHKENT', 'TAV', 'TB',
  'TBIT', 'TBMA', 'TBS POLAND', 'TC', 'TCC', 'TCM', 'TD', 'TE', 'TEF', 'TEHERAN',
  'TEL AVIV', 'TF', 'TFE', 'TFX', 'TG', 'TGE', 'TH', 'THAILAND', 'THIRD MKT CORP', 'TI',
  'TIDX', 'TISE', 'TJ', 'TJ21', 'TJV1', 'TK', 'TL', 'TLX', 'TN', 'TO',
  'TOKYO', 'TOKYO 2', 'TOM', 'TORONTO', 'TP', 'TQ', 'TR', 'TRACE', 'TRADEGATE', 'TRCK',
  'TRINIDAD&TOBAGO', 'TS', 'TSE', 'TSX VENTURE', 'TT', 'TTC', 'TU', 'TUNIS', 'TV', 'TW',
  'TX', 'TY', 'TZ', 'UA', 'UB', 'UC', 'UD', 'UE', 'UF', 'UG',
  'UGANDA', 'UH', 'UI', 'UJ', 'UK', 'UKR', 'UKRAINIAN EXCH', 'UL', 'UM', 'UN',
  'UNKNOWN', 'UO', 'UP', 'UPBT', 'upbt', 'UQ', 'UR', 'URCEX', 'US', 'USE',
  'USP2', 'usp2', 'USP3', 'usp3', 'UT', 'UU', 'UV', 'UW', 'UX', 'UY',
  'UZ', 'VA', 'VALENCIA', 'VARAZDIN', 'VB', 'VC', 'VE', 'VF', 'VG', 'VH',
  'VI', 'VIENNA', 'VJ', 'VK', 'VL', 'VM', 'VN', 'Vorvel', 'VP', 'VR',
  'VS', 'VU', 'VX', 'VY', 'WARSAW', 'WBA', 'WCE', 'WEXN', 'WHBT', 'WSE',
  'WT', 'WTB', 'WX', 'X1', 'X2', 'X9', 'XA', 'XB', 'XBTR', 'XC',
  'XD', 'XE', 'XETRA', 'XF', 'XG', 'XH', 'XI', 'XJ', 'XK', 'XL',
  'XM', 'XN', 'XO', 'XP', 'XQ', 'XR', 'XS', 'XT', 'XU', 'XV',
  'XW', 'XX', 'XY', 'XZ', 'YC', 'YELLOW SHEETS', 'YLX', 'YOBT', 'yobt', 'YSE',
  'ZA', 'ZAGREB', 'ZAIF', 'zaif', 'ZB', 'ZBCN', 'zbcn', 'ZC', 'ZCE', 'ZG',
  'ZH', 'ZIMBABWE', 'ZL', 'ZS', 'ZU',
]).or(z.string())

export const CurrencySchema = z.enum([
  '***', 'ADP', 'AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'ATS',
  'AUD', 'AUd', 'AWG', 'AZM', 'AZN', 'BAM', 'BBD', 'BDT', 'BEF', 'BGN',
  'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BRl', 'BSD', 'BTN', 'BWP',
  'BWp', 'BYN', 'BYR', 'BYS', 'BZD', 'CAD', 'CAd', 'CDF', 'CER', 'CHF',
  'CHf', 'CLF', 'CLP', 'CNH', 'CNT', 'CNY', 'COP', 'COU', 'CRC', 'CRS',
  'CUP', 'CVE', 'CYP', 'CZK', 'DEM', 'DJF', 'DKK', 'DOP', 'DZD', 'ECS',
  'EEK', 'EES', 'EGD', 'EGP', 'ERN', 'ESP', 'ETB', 'EUA', 'EUR', 'EUr',
  'FIM', 'FJD', 'FKP', 'FRF', 'GBP', 'GBp', 'GEL', 'GHC', 'GHS', 'GIP',
  'GLD', 'GMD', 'GNF', 'GRD', 'GTQ', 'GWP', 'GYD', 'HKD', 'HNL', 'HRK',
  'HTG', 'HUF', 'IDR', 'IEP', 'ILS', 'ILs', 'INR', 'IQD', 'IRR', 'ISK',
  'ITL', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW',
  'KRW', 'KWD', 'KWd', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL',
  'LTL', 'LUF', 'LVL', 'LYD', 'MAD', 'MDL', 'MGA', 'MGF', 'MKD', 'MLF',
  'MMK', 'MNT', 'MOP', 'MRO', 'MRU', 'MTL', 'MULTI', 'MUR', 'MVR', 'MWK',
  'MWk', 'MXN', 'MYR', 'MYr', 'MZM', 'MZN', 'NAD', 'NAd', 'NGN', 'NIC',
  'NID', 'NIO', 'NLG', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK',
  'PHP', 'PKR', 'PLD', 'PLN', 'PLT', 'PTE', 'PYG', 'QAR', 'ROL', 'RON',
  'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDD', 'SDG', 'SDP', 'SDR',
  'SEK', 'SGD', 'SGd', 'SHP', 'SIT', 'SKK', 'SLE', 'SLL', 'SLV', 'SOS',
  'SPL', 'SRD', 'SRG', 'SSP', 'STD', 'STN', 'SVC', 'SYP', 'SZL', 'SZl',
  'THB', 'THO', 'TJS', 'TMM', 'TMT', 'TND', 'TOP', 'TPE', 'TRL', 'TRY',
  'TTD', 'TVD', 'TWD', 'TZS', 'UAH', 'UDI', 'UGX', 'US', 'USD', 'USd',
  'UVR', 'UYI', 'UYU', 'UYW', 'UZS', 'VEB', 'VEE', 'VEF', 'VES', 'VND',
  'VUV', 'WST', 'X0S', 'X1S', 'X2S', 'X3S', 'X4S', 'X5S', 'X6S', 'X7S',
  'X8S', 'X9S', 'XAD', 'XAF', 'XAG', 'XAL', 'XAO', 'XAS', 'XAU', 'XAV',
  'XBA', 'XBI', 'XBN', 'XBS', 'XBT', 'XBW', 'XCD', 'XCG', 'XCR', 'XCS',
  'XCU', 'XDG', 'XDH', 'XDI', 'XDO', 'XDR', 'XDT', 'XEG', 'XEN', 'XEO',
  'XET', 'XEU', 'XFI', 'XFL', 'XFM', 'XFT', 'XGZ', 'XHB', 'XIC', 'XIN',
  'XIO', 'XLC', 'XLI', 'XLM', 'XLU', 'XMA', 'XMK', 'XMN', 'XMR', 'XNI',
  'XOF', 'XPB', 'XPD', 'XPF', 'XPT', 'XRA', 'XRH', 'XRI', 'XRP', 'XRU',
  'XSA', 'XSN', 'XSO', 'XST', 'XSU', 'XSZ', 'XTH', 'XTK', 'XTR', 'XUC',
  'XUN', 'XUT', 'XVC', 'XVV', 'XXT', 'XZC', 'XZI', 'YER', 'ZAR', 'ZAr',
  'ZMK', 'ZMW', 'ZWD', 'ZWd', 'ZWF', 'ZWG', 'ZWg', 'ZWL', 'ZWN', 'ZWR',
]).or(z.string())

export const MicCodeSchema = z.enum([
  '24EQ', 'A2XX', 'ACEX', 'ADRK', 'AFET', 'AIXK', 'AMTS', 'AMXO', 'APEX', 'APXL',
  'AQEU', 'AQSE', 'AQXE', 'ARCO', 'ARCX', 'ARTX', 'ASXP', 'BATE', 'BATO', 'BATS',
  'BATY', 'BCSE', 'BEUE', 'BFEX', 'BIVA', 'BJSE', 'BLOX', 'BMFM', 'BMTF', 'BMTS',
  'BOAT', 'BOTC', 'BSEX', 'BTFE', 'BURM', 'BVCA', 'BVMF', 'C2OX', 'CAPA', 'CCFX',
  'CEDX', 'CEUX', 'CHIA', 'CHIC', 'CHIJ', 'CHIX', 'CMED', 'CSE2', 'DGCX', 'DIFX',
  'DKED', 'DKTC', 'DSMD', 'DUMX', 'EBMX', 'ECEU', 'EDGA', 'EDGO', 'EDGX', 'EMLD',
  'EMTF', 'EMTS', 'ENAX', 'EPRL', 'ERIS', 'ETLX', 'EUCH', 'EUWX', 'EXGM', 'FISH',
  'FMTS', 'FNDK', 'FNFI', 'FNFT', 'FNIS', 'FNSE', 'FRAB', 'FREX', 'GBOT', 'GEMX',
  'GMEG', 'GMNI', 'GSXL', 'HKME', 'HMTF', 'HOTC', 'HSTC', 'ICDX', 'ICEL', 'ICXL',
  'IEPA', 'IEXG', 'IFAD', 'IFCA', 'IFED', 'IFEU', 'IFLL', 'IFLO', 'IFLX', 'IFSG',
  'IFUS', 'IINX', 'IMTS', 'INSE', 'LEUE', 'LICA', 'LIQU', 'LNEQ', 'LSSI', 'LTSE',
  'LYNX', 'MALX', 'MARF', 'MATN', 'MCAD', 'MCRY', 'MCXX', 'MEMX', 'MFOX', 'MISX',
  'MOTX', 'MPRL', 'MSAX', 'MTAA', 'MTAH', 'MTCH', 'MTSC', 'MTSD', 'MTSF', 'MUND',
  'MXOP', 'N2EX', 'NASX', 'NCEL', 'NDEX', 'NEOE', 'NEXX', 'NILX', 'NORX', 'NOTC',
  'NXTE', 'NZFX', 'OCEA', 'ODXE', 'OMGA', 'OMIP', 'OOTC', 'OPEX', 'OTCM', 'OTXB',
  'PDEX', 'PFTQ', 'PFTS', 'PLPD', 'PLUS', 'PURE', 'ROCO', 'ROFX', 'ROTC', 'RTSX',
  'RUSX', 'SBIJ', 'SBIU', 'SBMF', 'SEDX', 'SEND', 'SGMU', 'SGMX', 'SHSC', 'SIMV',
  'SMEX', 'SPHR', 'SPIM', 'SZSC', 'TBSP', 'TFEX', 'TOMX', 'TQEX', 'TREA', 'TREU',
  'TRNL', 'TRPX', 'TRQX', 'TWEA', 'TWEM', 'UKEX', 'WDER', 'WMTF', 'XADE', 'XADF',
  'XADS', 'XAIM', 'XALG', 'XAMM', 'XAMS', 'XAPA', 'XARM', 'XASE', 'XASX', 'XATH',
  'XATS', 'XATX', 'XBAA', 'XBAB', 'XBAH', 'XBAN', 'XBAR', 'XBBJ', 'XBCL', 'XBCM',
  'XBCV', 'XBCX', 'XBDA', 'XBDV', 'XBEL', 'XBER', 'XBES', 'XBEY', 'XBIL', 'XBKK',
  'XBLB', 'XBLN', 'XBNV', 'XBOG', 'XBOL', 'XBOM', 'XBOS', 'XBOT', 'XBOX', 'XBRA',
  'XBRD', 'XBRN', 'XBRU', 'XBRV', 'XBSD', 'XBSE', 'XBTR', 'XBUD', 'XBUE', 'XBUL',
  'XBVC', 'XBVM', 'XBVR', 'XBXO', 'XCAI', 'XCAS', 'XCAY', 'XCBF', 'XCBO', 'XCBT',
  'XCCX', 'XCEC', 'XCEG', 'XCFE', 'XCHG', 'XCHI', 'XCIE', 'XCIS', 'XCME', 'XCNQ',
  'XCOL', 'XCSE', 'XCSX', 'XCUE', 'XCX2', 'XCXD', 'XCYS', 'XDAR', 'XDCE', 'XDES',
  'XDFM', 'XDHA', 'XDMI', 'XDPA', 'XDRF', 'XDSE', 'XDSX', 'XDUB', 'XDUS', 'XECM',
  'XECS', 'XEEE', 'XELX', 'XEMD', 'XEQT', 'XETR', 'XEUE', 'XEUR', 'XFEX', 'XFKA',
  'XFM', 'XFRA', 'XGAT', 'XGHA', 'XGME', 'XGSE', 'XGTG', 'XGUA', 'XHAM', 'XHAN',
  'XHEL', 'XHFT', 'XHKF', 'XHKG', 'XHNF', 'XHNX', 'XICE', 'XICX', 'XIDX', 'XIMC',
  'XINE', 'XIQS', 'XISA', 'XIST', 'XISX', 'XJAM', 'XJAS', 'XJAX', 'XJSE', 'XKAC',
  'XKAR', 'XKAZ', 'XKBT', 'XKEM', 'XKFB', 'XKFE', 'XKHA', 'XKIS', 'XKLS', 'XKON',
  'XKOS', 'XKRX', 'XKSE', 'XKUW', 'XLAO', 'XLDN', 'XLFX', 'XLIM', 'XLIS', 'XLIT',
  'XLJU', 'XLME', 'XLOD', 'XLON', 'XLUS', 'XLUX', 'XMAB', 'XMAD', 'XMAE', 'XMAL',
  'XMAN', 'XMAT', 'XMAU', 'XMCE', 'XMDS', 'XMEV', 'XMEX', 'XMGE', 'XMIO', 'XMNT',
  'XMNX', 'XMOC', 'XMOD', 'XMOL', 'XMON', 'XMOS', 'XMOT', 'XMPW', 'XMRV', 'XMSW',
  'XMTB', 'XMUN', 'XMUS', 'XNAI', 'XNAM', 'XNAS', 'XNCD', 'XNCM', 'XNDQ', 'XNDX',
  'XNEC', 'XNEP', 'XNGM', 'XNGO', 'XNGS', 'XNIM', 'XNKS', 'XNLX', 'XNMS', 'XNSA',
  'XNSE', 'XNYM', 'XNYS', 'XNZE', 'XOAM', 'XOCH', 'XOPV', 'XOSE', 'XOSL', 'XOTC',
  'XPAE', 'XPAR', 'XPBT', 'XPHL', 'XPHS', 'XPIC', 'XPOM', 'XPOR', 'XPOS', 'XPOW',
  'XPRA', 'XPSX', 'XPTY', 'XQMH', 'XQTX', 'XQUI', 'XRAS', 'XRBM', 'XRIS', 'XRMZ',
  'XROS', 'XSAF', 'XSAM', 'XSAP', 'XSAT', 'XSAU', 'XSBI', 'XSCE', 'XSDX', 'XSEC',
  'XSES', 'XSFE', 'XSGE', 'XSGO', 'XSHE', 'XSHG', 'XSIM', 'XSMP', 'XSPS', 'XSRM',
  'XSSC', 'XSSE', 'XSTC', 'XSTE', 'XSTO', 'XSTU', 'XSVA', 'XSWA', 'XSWX', 'XTAE',
  'XTAF', 'XTAI', 'XTAL', 'XTEH', 'XTFF', 'XTKO', 'XTKS', 'XTKT', 'XTRN', 'XTSE',
  'XTSX', 'XTUN', 'XUBS', 'XUGA', 'XULA', 'XUSE', 'XVAL', 'XVPA', 'XVTX', 'XWAR',
  'XWBO', 'XZAG', 'XZCE', 'XZIM', 'YLDX', 'YYYY', 'ZFXM',
]).or(z.string())

export const SecurityTypeSchema = z.enum([
  'ABS Auto',
  'ABS Card',
  'ABS Home',
  'ABS Other',
  'ACCEPT BANCARIA',
  'ADJ CONV. TO FIXED',
  'ADJ CONV. TO FIXED, OID',
  'ADJUSTABLE',
  'ADJUSTABLE, OID',
  'ADR',
  'Agncy ABS Home',
  'Agncy ABS Other',
  'Agncy CMBS',
  'Agncy CMO FLT',
  'Agncy CMO INV',
  'Agncy CMO IO',
  'Agncy CMO Other',
  'Agncy CMO PO',
  'Agncy CMO Z',
  'Asset-Based',
  'ASSET-BASED BRIDGE',
  'ASSET-BASED BRIDGE REV',
  'ASSET-BASED BRIDGE TERM',
  'ASSET-BASED DELAY-DRAW TERM',
  'ASSET-BASED DIP',
  'ASSET-BASED DIP DELAY-DRAW',
  'ASSET-BASED DIP REV',
  'ASSET-BASED DIP TERM',
  'ASSET-BASED LOC',
  'ASSET-BASED PIK REV',
  'ASSET-BASED PIK TERM',
  'ASSET-BASED REV',
  'ASSET-BASED TERM',
  'AUSTRALIAN',
  'AUSTRALIAN CD',
  'AUSTRALIAN CP',
  'Austrian Crt',
  'BANK ACCEPT BILL',
  'BANK BILL',
  'BANK NOTE',
  'BANKERS ACCEPT',
  'BANKERS ACCEPTANCE',
  'BASIS SWAP',
  'BASIS TRADE ON CLOSE',
  'Basket WRT',
  'BDR',
  'BEARER DEP NOTE',
  'Belgium Cert',
  'BELGIUM CP',
  'BILL OF EXCHANGE',
  'BILLET A ORDRE',
  'Bond',
  'BRAZIL GENERIC',
  'BRAZILIAN CDI',
  'BRIDGE',
  'BRIDGE DELAY-DRAW',
  'BRIDGE DELAY-DRAW TERM',
  'BRIDGE DIP TERM',
  'BRIDGE GUARANTEE FAC',
  'BRIDGE ISLAMIC',
  'BRIDGE ISLAMIC TERM',
  'BRIDGE PIK',
  'BRIDGE PIK REV',
  'BRIDGE PIK TERM',
  'BRIDGE REV',
  'BRIDGE REV GUARANTEE FAC',
  'BRIDGE STANDBY TERM',
  'BRIDGE TERM',
  'BRIDGE TERM GUARANTEE FAC',
  'BRIDGE TERM VAT-TRNCH',
  'BRIDGE VAT-TRNCH',
  'BULLDOG',
  'BUTTERFLY SWAP',
  'CAD INT BEAR CP',
  'CALC_INSTRUMENT',
  'Calendar Spread Option',
  'CALL LOANS',
  'CALLABLE CP',
  'CANADIAN',
  'Canadian',
  'CANADIAN CD',
  'CANADIAN CP',
  'Canadian DR',
  'CAPS & FLOORS',
  'Car Forward',
  'CASH',
  'CASH FLOW',
  'CASH FLOW, OID',
  'CASH RATE',
  'CBLO',
  'CD',
  'CDI',
  'CDR',
  'CEDEAR',
  'CF',
  'CHILEAN CD',
  'CHILEAN DN',
  'Closed-End Fund',
  'CMBS',
  'Cmdt Fut WRT',
  'Cmdt Idx WRT',
  'COLLAT CALL NOTE',
  'COLOMBIAN CD',
  'COMMERCIAL NOTE',
  'COMMERCIAL PAPER',
  'Commodity Index',
  'Common Stock',
  'CONTRACT FOR DIFFERENCE',
  'CONTRACT FRA',
  'Conv Bond',
  'Conv Prfd',
  'Corp Bnd WRT',
  'Cover Pool',
  'CP-LIKE EXT NOTE',
  'CPI LINKED',
  'CROSS',
  'Crypto',
  'Currency future.',
  'Currency option.',
  'Currency spot.',
  'Currency WRT',
  'CURVE_ROLL',
  'DELAY-DRAW',
  'DELAY-DRAW ISLAMIC',
  'DELAY-DRAW ISLAMIC LOC',
  'DELAY-DRAW ISLAMIC TERM',
  'DELAY-DRAW LOC',
  'DELAY-DRAW PIK TERM',
  'DELAY-DRAW STANDBY TERM',
  'DELAY-DRAW TERM',
  'DELAY-DRAW TERM GUARANTEE F',
  'DELAY-DRAW TERM VAT-TRNCH',
  'DEPOSIT',
  'DEPOSIT NOTE',
  'DIM SUM BRIDGE TERM',
  'DIM SUM DELAY-DRAW TERM',
  'DIM SUM REV',
  'DIM SUM TERM',
  'DIP',
  'DIP DELAY-DRAW ISLAMIC TERM',
  'DIP DELAY-DRAW PIK TERM',
  'DIP DELAY-DRAW TERM',
  'DIP LOC',
  'DIP PIK TERM',
  'DIP REV',
  'DIP STANDBY LOC',
  'DIP SYNTH LOC',
  'DIP TERM',
  'DISCOUNT FIXBIS',
  'DISCOUNT NOTES',
  'DIVIDEND NEUTRAL STOCK FUTURE',
  'DOMESTC TIME DEP',
  'DOMESTIC',
  'DOMESTIC MTN',
  'Dutch Cert',
  'DUTCH CP',
  'EDR',
  'Equity Index',
  'Equity Option',
  'Equity WRT',
  'ETP',
  'EURO CD',
  'EURO CP',
  'EURO MTN',
  'EURO NON-DOLLAR',
  'EURO STRUCTRD LN',
  'EURO TIME DEPST',
  'EURO-DOLLAR',
  'EURO-ZONE',
  'EXTEND COMM NOTE',
  'EXTEND. NOTE MTN',
  'FDIC',
  'FED FUNDS',
  'FIDC',
  'Financial commodity future.',
  'Financial commodity generic.',
  'Financial commodity option.',
  'Financial commodity spot.',
  'Financial index future.',
  'Financial index generic.',
  'Financial index option.',
  'FINNISH CD',
  'FINNISH CP',
  'FIXED',
  'Fixed Income Index',
  'FIXED, OID',
  'FIXING RATE',
  'FLOATING',
  'FLOATING CP',
  'FLOATING, OID',
  'FNMA FHAVA',
  'Foreign Sh.',
  'FORWARD',
  'FORWARD CROSS',
  'FORWARD CURVE',
  'FRA',
  'FRENCH CD',
  'French Cert',
  'FRENCH CP',
  'Fund of Funds',
  'Futures Monthly Ticker',
  'FWD SWAP',
  'FX Curve',
  'FX DISCOUNT NOTE',
  'GDR',
  'Generic currency future.',
  'Generic index future.',
  'German Cert',
  'GERMAN CP',
  'GLOBAL',
  'GUARANTEE FAC',
  'HB',
  'HDR',
  'HONG KONG CD',
  'I.R. Fut WRT',
  'I.R. Swp WRT',
  'IDR',
  'IMM FORWARD',
  'IMM SWAP',
  'Index',
  'Index Option',
  'Index WRT',
  'INDIAN CD',
  'INDIAN CP',
  'INDONESIAN CP',
  'Indx Fut WRT',
  'INFLATION SWAP',
  'INT BEAR FIXBIS',
  'Int. Rt. WRT',
  'INTER. APPRECIATION',
  'INTER. APPRECIATION, OID',
  'ISLAMIC',
  'ISLAMIC BA',
  'ISLAMIC CP',
  'ISLAMIC GUARANTEE FAC',
  'ISLAMIC LOC',
  'ISLAMIC REV',
  'ISLAMIC STANDBY',
  'ISLAMIC STANDBY REV',
  'ISLAMIC STANDBY TERM',
  'ISLAMIC TERM',
  'ISLAMIC TERM GUARANTEE FAC',
  'ISLAMIC TERM VAT-TRNCH',
  'JUMBO CD',
  'KOREAN CD',
  'KOREAN CP',
  'LEBANESE CP',
  'LIQUIDITY NOTE',
  'LOC',
  'LOC GUARANTEE FAC',
  'LOC TERM',
  'Ltd Part',
  'MALAYSIAN CP',
  'Managed Account',
  'MARGIN TERM DEP',
  'MASTER NOTES',
  'MBS 10yr',
  'MBS 15yr',
  'MBS 20yr',
  'MBS 30yr',
  'MBS 35yr',
  'MBS 40yr',
  'MBS 50yr',
  'MBS 5yr',
  'MBS 7yr',
  'MBS ARM',
  'MBS balloon',
  'MBS Other',
  'MED TERM NOTE',
  'MEDIUM TERM CD',
  'MEDIUM TERM ECD',
  'MEXICAN CP',
  'MEXICAN PAGARE',
  'Misc.',
  'MLP',
  'MONETARY BILLS',
  'MONEY MARKET CALL',
  'MUNI CP',
  'MUNI INT BEAR CP',
  'MUNI SWAP',
  'MURABAHA',
  'Mutual Fund',
  'MV',
  'MX CERT BURSATIL',
  'NDF SWAP',
  'NEG EURO CP',
  'NEG INST DEPOSIT',
  'NEGOTIABLE CD',
  'NEW ZEALAND CD',
  'NEW ZEALAND CP',
  'NON-DELIVERABLE FORWARD',
  'NON-DELIVERABLE IRS SWAP',
  'NVDR',
  'NY Reg Shrs',
  'OID',
  'ONSHORE FORWARD',
  'ONSHORE SWAP',
  'Open-End Fund',
  'OPTION',
  'Option on Equity Future',
  'OPTION VOLATILITY',
  'OTHER',
  'OVER/NIGHT',
  'OVERDRAFT',
  'OVERNIGHT INDEXED SWAP',
  'PANAMANIAN CP',
  'Participate Cert',
  'PHILIPPINE CP',
  'Physical commodity forward.',
  'Physical commodity future.',
  'Physical commodity generic.',
  'Physical commodity option.',
  'Physical commodity spot.',
  'Physical index future.',
  'Physical index option.',
  'PIK',
  'PIK LOC',
  'PIK REV',
  'PIK SYNTH LOC',
  'PIK TERM',
  'PLAZOS FIJOS',
  'PORTUGUESE CP',
  'Preference',
  'Preferred',
  'PRES',
  'Prfd WRT',
  'PRIV PLACEMENT',
  'PRIVATE',
  'Private Comp',
  'Private-equity backed',
  'PROMISSORY NOTE',
  'PROV T-BILL',
  'Prvt CMBS',
  'Prvt CMO FLT',
  'Prvt CMO INV',
  'Prvt CMO IO',
  'Prvt CMO Other',
  'Prvt CMO PO',
  'Prvt CMO Z',
  'PUBLIC',
  'Pvt Eqty Fund',
  'RDC',
  'Receipt',
  'REIT',
  'REPO',
  'RESERVE-BASED DIP REV',
  'RESERVE-BASED LOC',
  'RESERVE-BASED REV',
  'RESERVE-BASED TERM',
  'RESTRUCTURD DEBT',
  'RETAIL CD',
  'RETURN IDX',
  'REV',
  'REV GUARANTEE FAC',
  'REV VAT-TRNCH',
  'Revolver',
  'Right',
  'Royalty Trst',
  'S.TERM LOAN NOTE',
  'SAMURAI',
  'Savings Plan',
  'Savings Share',
  'SBA Pool',
  'SDR',
  'Sec Lending',
  'SHOGUN',
  'SHORT TERM BN',
  'SHORT TERM DN',
  'SINGAPORE CP',
  'Singapore DR',
  'SINGLE STOCK DIVIDEND FUTURE',
  'SINGLE STOCK FORWARD',
  'SINGLE STOCK FUTURE',
  'SINGLE STOCK FUTURE SPREAD',
  'SN',
  'SPANISH CP',
  'SPECIAL LMMK PGM',
  'SPOT',
  'Spot index.',
  'STANDBY',
  'STANDBY LOC',
  'STANDBY LOC GUARANTEE FAC',
  'STANDBY REV',
  'STANDBY TERM',
  'Stapled Security',
  'STERLING CD',
  'STERLING CP',
  'Strategy Trade.',
  'SWAP',
  'SWAP SPREAD',
  'SWAPTION VOLATILITY',
  'SWEDISH CP',
  'SWINGLINE',
  'Swiss Cert',
  'SYNTH LOC',
  'SYNTH REV',
  'SYNTH TERM',
  'Synthetic Term',
  'TAIWAN CP',
  'TAIWAN CP GUAR',
  'TAIWAN NEGO CD',
  'TAIWAN TIME DEPO',
  'TAX CREDIT',
  'TAX CREDIT, OID',
  'TDR',
  'TERM',
  'TERM DEPOSITS',
  'TERM GUARANTEE FAC',
  'TERM REV',
  'TERM VAT-TRNCH',
  'THAILAND CP',
  'TLTRO TERM',
  'Tracking Stk',
  'TREASURY BILL',
  'U.S. CD',
  'U.S. CP',
  'U.S. INT BEAR CP',
  'UIT',
  'UK GILT STOCK',
  'UMBS MBS Other',
  'Unit',
  'Unit Inv Tst',
  'UNITRANCHE',
  'UNITRANCHE ASSET-BASED REV',
  'UNITRANCHE DELAY-DRAW PIK T',
  'UNITRANCHE DELAY-DRAW TERM',
  'UNITRANCHE PIK REV',
  'UNITRANCHE PIK TERM',
  'UNITRANCHE REV',
  'UNITRANCHE TERM',
  'US DOMESTIC',
  'US GOVERNMENT',
  'US NON-DOLLAR',
  'VAR RATE DEM OBL',
  'VAT-TRNCH',
  'VENEZUELAN CP',
  'VIETNAMESE CD',
  'VOLATILITY DERIVATIVE',
  'Warrant',
  'YANKEE',
  'YANKEE CD',
  'YEN CD',
  'YEN CP',
  'Yield Curve',
  'ZERO COUPON',
  'ZERO COUPON, OID',
]).or(z.string())

export const SecurityType2Schema = z.enum([
  '2ND LIEN',
  'ABS',
  'ABS Other',
  'ABS/HG',
  'ABS/MEZZ',
  'BA',
  'Bagged Briquettes',
  'Bagged Pellets',
  'BANK BILL',
  'BANKERS ACCEPTANCE',
  'BASIS',
  'BASIS SWAP',
  'BASIS_IMM',
  'Bill',
  'Billet 20MN',
  'Billet 3803p',
  'Billet 3803s',
  'Billet 3803sp',
  'Billet 3805p',
  'Billet 3805s',
  'Billet 3805sp',
  'Billet A61560',
  'Billet BS4449',
  'Billet LME Grade 1',
  'Billet LME Grade 2',
  'Billet LME Grade 3',
  'Billet LME Grade 4',
  'Billet LME Grade 5',
  'Billet LME Grade 6',
  'Billet LME Grade 7',
  'Billet LME Grade 8',
  'Billet LME Grade 9',
  'Billet Q235',
  'BN',
  'Bond',
  'Bond/Note',
  'Briquettes',
  'BUTTERFLY SWAP',
  'CAPFLOOR',
  'CAPFLOOR_RFR',
  'CAPS & FLOORS',
  'CASH RATE',
  'Cathodes',
  'Cathodes 100x100mm',
  'Cathodes 25x25mm',
  'Cathodes 50x50mm',
  'CD',
  'CDO2',
  'CDS',
  'CDS(CRP)',
  'Certificate',
  'CMBS',
  'CMO',
  'Coarse Grain Powder',
  'Comdty',
  'COMMERCIAL PAPER',
  'Common Stock',
  'CONTRACT FRA',
  'Corp',
  'CP',
  'CRE',
  'CROSS',
  'CROSS_CURRENCY_BASIS',
  'CROSS_CURRENCY_FIXED_FLOAT',
  'CRYPTO',
  'Curncy',
  'Daily Future',
  'DEPOSIT',
  'Depositary Receipt',
  'Derived',
  'DN',
  'Equity',
  'FDIC',
  'FIXED_FLOAT',
  'FIXED_FLOAT_FORWARD_STARTING',
  'FIXED_FLOAT_OIS',
  'FIXING RATE',
  'FORWARD',
  'FORWARD CROSS',
  'FORWARD CURVE',
  'FORWARD_START_SWAP',
  'FRA',
  'Full Plate Cathodes',
  'Future',
  'FWD SWAP',
  'FX Curve',
  'Generic',
  'Govt',
  'Granules',
  'Hedged',
  'HF',
  'HY',
  'IG',
  'IMM FORWARD',
  'IMM SWAP',
  'Index',
  'INFL_FIXING_ZERO_COUPON',
  'INFL_FXFL_ZERO_COUPON',
  'INFLATION SWAP',
  'INFLATION_SWAP',
  'Ingots',
  'Ingots 226/DIN',
  'Ingots A380.1',
  'Ingots AD12.1',
  'Ingots D12S/J1S',
  'Jumbo',
  'Large Sows',
  'Large sows 226',
  'Large sows A380.1',
  'Large sows AD12.1',
  'Large sows D12S',
  'LL',
  'LL08',
  'M-Mkt',
  'MAC SWAP',
  'MAC_RFR',
  'MEZZ',
  'MML',
  'Molybdenum Cntd n RMC(Roasted',
  'MONEY MARKET CALL',
  'Mtge',
  'MTN',
  'Muni',
  'MUNI SWAP',
  'Mutual Fund',
  'NDF SWAP',
  'NDOIS',
  'Nickel Rounds',
  'Nickel Rounds Bag',
  'NON-DELIVERABLE FORWARD',
  'NON-DELIVERABLE IRS SWAP',
  'NON-DELIVERABLE OIS SWAP',
  'Note',
  'ONSHORE FORWARD',
  'ONSHORE SWAP',
  'Option',
  'OPTION VOLATILITY',
  'OTHER',
  'OVERNIGHT INDEXED SWAP',
  'PAIR',
  'PAR_RATE',
  'Partnership Shares',
  'Pellets',
  'Pool',
  'PP12',
  'PP20',
  'PP25',
  'PP3.5',
  'Preference',
  'Preferred Stock',
  'PROMISSORY NOTE',
  'Prompt Forward',
  'PROPERTY SWAP',
  'QUARTERLY SWAP',
  'REIT',
  'REPO',
  'RETURN IDX',
  'Right',
  'RMBS',
  'Rounds',
  'Small Sows',
  'Small sows 226',
  'Small sows A380.1',
  'Small sows AD12.1',
  'Small sows D12S',
  'SME',
  'Sows',
  'SPOT',
  'SWAP',
  'SWAP SPREAD',
  'SWAPTION',
  'SWAPTION VOLATILITY',
  'T-Bar',
  'T-Bars 226',
  'T-Bars A380.1',
  'T-Bars AD12.1',
  'T-Bars D12S',
  'TBA',
  'TD',
  'TREASURY BILL',
  'TRP',
  'Unit',
  'Unit Investment Trust',
  'VOLATILITY DERIVATIVE',
  'Warrant',
  'Whole Loan',
  'Yield Curve',
  'ZERO_COUPON_OIS_SWAP',
]).or(z.string())

export const MarketSectorSchema = z.enum([
  'Comdty',
  'Corp',
  'Curncy',
  'Equity',
  'Govt',
  'Index',
  'M-Mkt',
  'Mtge',
  'Muni',
  'Pfd',
]).or(z.string())

export const StateCodeSchema = z.enum([
  'AB', 'AC', 'AH', 'AK', 'AL', 'AM', 'AR', 'AS', 'AT', 'AZ',
  'BC', 'BJ', 'CA', 'CB', 'CO', 'CQ', 'CT', 'CZ', 'DC', 'DE',
  'EH', 'FH', 'FI', 'FJ', 'FL', 'FO', 'FS', 'GA', 'GD', 'GF',
  'GM', 'GS', 'GU', 'GX', 'GZ', 'HA', 'HB', 'HE', 'HG', 'HI',
  'HL', 'HN', 'HO', 'HS', 'IA', 'ID', 'IG', 'IK', 'IL', 'IN',
  'IT', 'JL', 'JS', 'JX', 'KA', 'KC', 'KN', 'KO', 'KS', 'KT',
  'KU', 'KY', 'LA', 'LN', 'MA', 'MB', 'MD', 'ME', 'MG', 'MI',
  'MN', 'MO', 'MS', 'MT', 'MZ', 'NB', 'NC', 'ND', 'NE', 'NG',
  'NH', 'NJ', 'NL', 'NM', 'NN', 'NR', 'NS', 'NT', 'NU', 'NV',
  'NW', 'NX', 'NY', 'OH', 'OK', 'ON', 'OR', 'OS', 'OT', 'OY',
  'PA', 'PE', 'PR', 'QC', 'QH', 'QL', 'RI', 'SA', 'SC', 'SD',
  'SH', 'SI', 'SK', 'SN', 'ST', 'SX', 'SZ', 'TA', 'TG', 'TJ',
  'TK', 'TN', 'TS', 'TT', 'TX', 'TY', 'UT', 'VA', 'VI', 'VT',
  'WA', 'WI', 'WK', 'WV', 'WY', 'XJ', 'XZ', 'YA', 'YN', 'YT',
  'YU', 'ZJ',
]).or(z.string())

export const MappingRequestSchema = z.object({
  idType: IdTypeSchema,
  idValue: z.string().min(1),
  exchCode: ExchCodeSchema.optional(),
  micCode: MicCodeSchema.optional(),
  currency: CurrencySchema.optional(),
  marketSecDes: MarketSectorSchema.optional(),
  securityType: SecurityTypeSchema.optional(),
  securityType2: SecurityType2Schema.optional(),
  includeUnlistedEquities: z.boolean().optional(),
  optionType: z.enum(['Put', 'Call']).or(z.string()).optional(),
  strike: z.array(z.number()).optional(),
  contractSize: z.number().optional(),
  coupon: z.array(z.number()).optional(),
  expiration: z.array(z.number()).optional(),
  maturity: z.array(z.number()).optional(),
  stateCode: StateCodeSchema.optional(),
})

export const FigiResultSchema = z.object({
  figi: z.string(),
  securityType: SecurityTypeSchema.optional(),
  marketSector: MarketSectorSchema.optional(),
  ticker: z.string().optional(),
  name: z.string().optional(),
  exchCode: ExchCodeSchema.optional(),
  shareClassFIGI: z.string().optional(),
  compositeFIGI: z.string().optional(),
  securityType2: SecurityType2Schema.optional(),
  securityDescription: z.string().optional(),
  metadata: z.string().optional(),
})

export const MappingResponseSchema = z.object({
  data: z.array(FigiResultSchema).optional(),
  warning: z.string().optional(),
  error: z.string().optional(),
})

export const ApiErrorSchema = z.object({
  error: z.string(),
  message: z.string().optional(),
  statusCode: z.number().optional(),
})

export const ClientConfigSchema = z.object({
  apiKey: z.string().optional(),
  baseUrl: z.string().url().optional(),
  timeout: z.number().positive().optional(),
  retryLimit: z.number().min(0).max(10).optional(),
  retryDelay: z.number().positive().optional(),
  userAgent: z.string().optional(),
})
